# =============================================================================
# PROFIL VIDE — Base H2 en mémoire + base vide à chaque démarrage
# =============================================================================
spring.datasource.url=jdbc:h2:mem:oaktime-vide;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# create-drop : les tables sont créées au démarrage et supprimées à l'arrêt
spring.jpa.hibernate.ddl-auto=create-drop

# Aucun script SQL chargé
spring.sql.init.mode=never
